Traceback (most recent call last):
  File "/root/repos/virus-report/spider/scheduler.py", line 23, in <module>
    sleep(nextScheduleTime)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repos/virus-report/spider/scheduler.py", line 41, in <module>
    saveData()
  File "/root/repos/virus-report/spider/utils.py", line 12, in saveData
    with open(sumPath,"w",errors='ignore',encoding='utf-8') as w:
NameError: name 'sumPath' is not defined
